version: '3.8'

services:
  reverse-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy  # Явно задаем имя контейнера
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"  # Важная метка
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d  
      - ./html:/usr/share/nginx/html
    networks:
      - app-network

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d  
      - ./html:/usr/share/nginx/html
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy  # Явно указываем имя контейнера
    depends_on:
      - reverse-proxy
    networks:
      - app-network

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    expose:
      - ${POSTGRES_PORT}
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      VIRTUAL_HOST: pgadmin.moninotools.ru
      LETSENCRYPT_HOST: pgadmin.moninotools.ru
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}

    networks:
      - app-network

  api:
    build: ./api
    environment:
      VIRTUAL_HOST: api.moninotools.ru
      LETSENCRYPT_HOST: api.moninotools.ru
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    volumes:
      - static-data:/app/static  # Монтируем volume в папку static
    depends_on:
      - db
    ports:
      - 5000:5000
    expose:
      - 5000
    networks:
      - app-network

  admin:
    build: ./admin
    environment:
      VIRTUAL_HOST: admin.moninotools.ru
      LETSENCRYPT_HOST: admin.moninotools.ru
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - app-network

  user:
    build: ./user
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      VIRTUAL_HOST: moninotools.ru
      LETSENCRYPT_HOST: moninotools.ru
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
    ports:
      - 4000:3000
    expose:
      - 4000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:  # Volume для PostgreSQL
  static-data:  # Volume для статических файлов API